// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtb2__Syms.h"


VL_ATTR_COLD void Vtb2___024root__trace_init_sub__TOP__0(Vtb2___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_init_sub__TOP__0\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("tb2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+781,0,"clk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"ph",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"rgb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+7,0,"enc_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"enc_rst_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("output_stream", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 320; ++i) {
        tracep->declBus(c+8+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("rgbstack", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 64; ++i) {
        tracep->declBus(c+328+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 11,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+392,0,"capped",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("enc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+781,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"rgb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->pushPrefix("output_stream", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 320; ++i) {
        tracep->declBus(c+8+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("rgbstack", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 64; ++i) {
        tracep->declBus(c+328+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 11,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+392,0,"capped",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("stream", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 320; ++i) {
        tracep->declBus(c+393+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+713,0,"stream_ind",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->pushPrefix("stack", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 64; ++i) {
        tracep->declBus(c+714+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 11,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+778,0,"stack_ind",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+779,0,"last_rgb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+782,0,"drgb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+780,0,"rcntr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+3,0,"r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+4,0,"g",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+5,0,"b",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtb2___024root__trace_init_top(Vtb2___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_init_top\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtb2___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtb2___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtb2___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtb2___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtb2___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtb2___024root__trace_register(Vtb2___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_register\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtb2___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtb2___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtb2___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtb2___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtb2___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_const_0\n"); );
    // Init
    Vtb2___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb2___024root*>(voidSelf);
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtb2___024root__trace_full_0_sub_0(Vtb2___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtb2___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_full_0\n"); );
    // Init
    Vtb2___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb2___024root*>(voidSelf);
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtb2___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtb2___024root__trace_full_0_sub_0(Vtb2___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb2___024root__trace_full_0_sub_0\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullSData(oldp+1,(vlSelfRef.tb2__DOT__rgb),12);
    bufp->fullBit(oldp+2,(vlSelfRef.tb2__DOT__enc_rst_n));
    bufp->fullCData(oldp+3,((0xfU & ((IData)(vlSelfRef.tb2__DOT__rgb) 
                                     >> 8U))),4);
    bufp->fullCData(oldp+4,((0xfU & ((IData)(vlSelfRef.tb2__DOT__rgb) 
                                     >> 4U))),4);
    bufp->fullCData(oldp+5,((0xfU & (IData)(vlSelfRef.tb2__DOT__rgb))),4);
    bufp->fullBit(oldp+6,(vlSelfRef.tb2__DOT__ph));
    bufp->fullBit(oldp+7,(vlSelfRef.tb2__DOT__enc_en));
    bufp->fullCData(oldp+8,(vlSelfRef.tb2__DOT__output_stream[0]),8);
    bufp->fullCData(oldp+9,(vlSelfRef.tb2__DOT__output_stream[1]),8);
    bufp->fullCData(oldp+10,(vlSelfRef.tb2__DOT__output_stream[2]),8);
    bufp->fullCData(oldp+11,(vlSelfRef.tb2__DOT__output_stream[3]),8);
    bufp->fullCData(oldp+12,(vlSelfRef.tb2__DOT__output_stream[4]),8);
    bufp->fullCData(oldp+13,(vlSelfRef.tb2__DOT__output_stream[5]),8);
    bufp->fullCData(oldp+14,(vlSelfRef.tb2__DOT__output_stream[6]),8);
    bufp->fullCData(oldp+15,(vlSelfRef.tb2__DOT__output_stream[7]),8);
    bufp->fullCData(oldp+16,(vlSelfRef.tb2__DOT__output_stream[8]),8);
    bufp->fullCData(oldp+17,(vlSelfRef.tb2__DOT__output_stream[9]),8);
    bufp->fullCData(oldp+18,(vlSelfRef.tb2__DOT__output_stream[10]),8);
    bufp->fullCData(oldp+19,(vlSelfRef.tb2__DOT__output_stream[11]),8);
    bufp->fullCData(oldp+20,(vlSelfRef.tb2__DOT__output_stream[12]),8);
    bufp->fullCData(oldp+21,(vlSelfRef.tb2__DOT__output_stream[13]),8);
    bufp->fullCData(oldp+22,(vlSelfRef.tb2__DOT__output_stream[14]),8);
    bufp->fullCData(oldp+23,(vlSelfRef.tb2__DOT__output_stream[15]),8);
    bufp->fullCData(oldp+24,(vlSelfRef.tb2__DOT__output_stream[16]),8);
    bufp->fullCData(oldp+25,(vlSelfRef.tb2__DOT__output_stream[17]),8);
    bufp->fullCData(oldp+26,(vlSelfRef.tb2__DOT__output_stream[18]),8);
    bufp->fullCData(oldp+27,(vlSelfRef.tb2__DOT__output_stream[19]),8);
    bufp->fullCData(oldp+28,(vlSelfRef.tb2__DOT__output_stream[20]),8);
    bufp->fullCData(oldp+29,(vlSelfRef.tb2__DOT__output_stream[21]),8);
    bufp->fullCData(oldp+30,(vlSelfRef.tb2__DOT__output_stream[22]),8);
    bufp->fullCData(oldp+31,(vlSelfRef.tb2__DOT__output_stream[23]),8);
    bufp->fullCData(oldp+32,(vlSelfRef.tb2__DOT__output_stream[24]),8);
    bufp->fullCData(oldp+33,(vlSelfRef.tb2__DOT__output_stream[25]),8);
    bufp->fullCData(oldp+34,(vlSelfRef.tb2__DOT__output_stream[26]),8);
    bufp->fullCData(oldp+35,(vlSelfRef.tb2__DOT__output_stream[27]),8);
    bufp->fullCData(oldp+36,(vlSelfRef.tb2__DOT__output_stream[28]),8);
    bufp->fullCData(oldp+37,(vlSelfRef.tb2__DOT__output_stream[29]),8);
    bufp->fullCData(oldp+38,(vlSelfRef.tb2__DOT__output_stream[30]),8);
    bufp->fullCData(oldp+39,(vlSelfRef.tb2__DOT__output_stream[31]),8);
    bufp->fullCData(oldp+40,(vlSelfRef.tb2__DOT__output_stream[32]),8);
    bufp->fullCData(oldp+41,(vlSelfRef.tb2__DOT__output_stream[33]),8);
    bufp->fullCData(oldp+42,(vlSelfRef.tb2__DOT__output_stream[34]),8);
    bufp->fullCData(oldp+43,(vlSelfRef.tb2__DOT__output_stream[35]),8);
    bufp->fullCData(oldp+44,(vlSelfRef.tb2__DOT__output_stream[36]),8);
    bufp->fullCData(oldp+45,(vlSelfRef.tb2__DOT__output_stream[37]),8);
    bufp->fullCData(oldp+46,(vlSelfRef.tb2__DOT__output_stream[38]),8);
    bufp->fullCData(oldp+47,(vlSelfRef.tb2__DOT__output_stream[39]),8);
    bufp->fullCData(oldp+48,(vlSelfRef.tb2__DOT__output_stream[40]),8);
    bufp->fullCData(oldp+49,(vlSelfRef.tb2__DOT__output_stream[41]),8);
    bufp->fullCData(oldp+50,(vlSelfRef.tb2__DOT__output_stream[42]),8);
    bufp->fullCData(oldp+51,(vlSelfRef.tb2__DOT__output_stream[43]),8);
    bufp->fullCData(oldp+52,(vlSelfRef.tb2__DOT__output_stream[44]),8);
    bufp->fullCData(oldp+53,(vlSelfRef.tb2__DOT__output_stream[45]),8);
    bufp->fullCData(oldp+54,(vlSelfRef.tb2__DOT__output_stream[46]),8);
    bufp->fullCData(oldp+55,(vlSelfRef.tb2__DOT__output_stream[47]),8);
    bufp->fullCData(oldp+56,(vlSelfRef.tb2__DOT__output_stream[48]),8);
    bufp->fullCData(oldp+57,(vlSelfRef.tb2__DOT__output_stream[49]),8);
    bufp->fullCData(oldp+58,(vlSelfRef.tb2__DOT__output_stream[50]),8);
    bufp->fullCData(oldp+59,(vlSelfRef.tb2__DOT__output_stream[51]),8);
    bufp->fullCData(oldp+60,(vlSelfRef.tb2__DOT__output_stream[52]),8);
    bufp->fullCData(oldp+61,(vlSelfRef.tb2__DOT__output_stream[53]),8);
    bufp->fullCData(oldp+62,(vlSelfRef.tb2__DOT__output_stream[54]),8);
    bufp->fullCData(oldp+63,(vlSelfRef.tb2__DOT__output_stream[55]),8);
    bufp->fullCData(oldp+64,(vlSelfRef.tb2__DOT__output_stream[56]),8);
    bufp->fullCData(oldp+65,(vlSelfRef.tb2__DOT__output_stream[57]),8);
    bufp->fullCData(oldp+66,(vlSelfRef.tb2__DOT__output_stream[58]),8);
    bufp->fullCData(oldp+67,(vlSelfRef.tb2__DOT__output_stream[59]),8);
    bufp->fullCData(oldp+68,(vlSelfRef.tb2__DOT__output_stream[60]),8);
    bufp->fullCData(oldp+69,(vlSelfRef.tb2__DOT__output_stream[61]),8);
    bufp->fullCData(oldp+70,(vlSelfRef.tb2__DOT__output_stream[62]),8);
    bufp->fullCData(oldp+71,(vlSelfRef.tb2__DOT__output_stream[63]),8);
    bufp->fullCData(oldp+72,(vlSelfRef.tb2__DOT__output_stream[64]),8);
    bufp->fullCData(oldp+73,(vlSelfRef.tb2__DOT__output_stream[65]),8);
    bufp->fullCData(oldp+74,(vlSelfRef.tb2__DOT__output_stream[66]),8);
    bufp->fullCData(oldp+75,(vlSelfRef.tb2__DOT__output_stream[67]),8);
    bufp->fullCData(oldp+76,(vlSelfRef.tb2__DOT__output_stream[68]),8);
    bufp->fullCData(oldp+77,(vlSelfRef.tb2__DOT__output_stream[69]),8);
    bufp->fullCData(oldp+78,(vlSelfRef.tb2__DOT__output_stream[70]),8);
    bufp->fullCData(oldp+79,(vlSelfRef.tb2__DOT__output_stream[71]),8);
    bufp->fullCData(oldp+80,(vlSelfRef.tb2__DOT__output_stream[72]),8);
    bufp->fullCData(oldp+81,(vlSelfRef.tb2__DOT__output_stream[73]),8);
    bufp->fullCData(oldp+82,(vlSelfRef.tb2__DOT__output_stream[74]),8);
    bufp->fullCData(oldp+83,(vlSelfRef.tb2__DOT__output_stream[75]),8);
    bufp->fullCData(oldp+84,(vlSelfRef.tb2__DOT__output_stream[76]),8);
    bufp->fullCData(oldp+85,(vlSelfRef.tb2__DOT__output_stream[77]),8);
    bufp->fullCData(oldp+86,(vlSelfRef.tb2__DOT__output_stream[78]),8);
    bufp->fullCData(oldp+87,(vlSelfRef.tb2__DOT__output_stream[79]),8);
    bufp->fullCData(oldp+88,(vlSelfRef.tb2__DOT__output_stream[80]),8);
    bufp->fullCData(oldp+89,(vlSelfRef.tb2__DOT__output_stream[81]),8);
    bufp->fullCData(oldp+90,(vlSelfRef.tb2__DOT__output_stream[82]),8);
    bufp->fullCData(oldp+91,(vlSelfRef.tb2__DOT__output_stream[83]),8);
    bufp->fullCData(oldp+92,(vlSelfRef.tb2__DOT__output_stream[84]),8);
    bufp->fullCData(oldp+93,(vlSelfRef.tb2__DOT__output_stream[85]),8);
    bufp->fullCData(oldp+94,(vlSelfRef.tb2__DOT__output_stream[86]),8);
    bufp->fullCData(oldp+95,(vlSelfRef.tb2__DOT__output_stream[87]),8);
    bufp->fullCData(oldp+96,(vlSelfRef.tb2__DOT__output_stream[88]),8);
    bufp->fullCData(oldp+97,(vlSelfRef.tb2__DOT__output_stream[89]),8);
    bufp->fullCData(oldp+98,(vlSelfRef.tb2__DOT__output_stream[90]),8);
    bufp->fullCData(oldp+99,(vlSelfRef.tb2__DOT__output_stream[91]),8);
    bufp->fullCData(oldp+100,(vlSelfRef.tb2__DOT__output_stream[92]),8);
    bufp->fullCData(oldp+101,(vlSelfRef.tb2__DOT__output_stream[93]),8);
    bufp->fullCData(oldp+102,(vlSelfRef.tb2__DOT__output_stream[94]),8);
    bufp->fullCData(oldp+103,(vlSelfRef.tb2__DOT__output_stream[95]),8);
    bufp->fullCData(oldp+104,(vlSelfRef.tb2__DOT__output_stream[96]),8);
    bufp->fullCData(oldp+105,(vlSelfRef.tb2__DOT__output_stream[97]),8);
    bufp->fullCData(oldp+106,(vlSelfRef.tb2__DOT__output_stream[98]),8);
    bufp->fullCData(oldp+107,(vlSelfRef.tb2__DOT__output_stream[99]),8);
    bufp->fullCData(oldp+108,(vlSelfRef.tb2__DOT__output_stream[100]),8);
    bufp->fullCData(oldp+109,(vlSelfRef.tb2__DOT__output_stream[101]),8);
    bufp->fullCData(oldp+110,(vlSelfRef.tb2__DOT__output_stream[102]),8);
    bufp->fullCData(oldp+111,(vlSelfRef.tb2__DOT__output_stream[103]),8);
    bufp->fullCData(oldp+112,(vlSelfRef.tb2__DOT__output_stream[104]),8);
    bufp->fullCData(oldp+113,(vlSelfRef.tb2__DOT__output_stream[105]),8);
    bufp->fullCData(oldp+114,(vlSelfRef.tb2__DOT__output_stream[106]),8);
    bufp->fullCData(oldp+115,(vlSelfRef.tb2__DOT__output_stream[107]),8);
    bufp->fullCData(oldp+116,(vlSelfRef.tb2__DOT__output_stream[108]),8);
    bufp->fullCData(oldp+117,(vlSelfRef.tb2__DOT__output_stream[109]),8);
    bufp->fullCData(oldp+118,(vlSelfRef.tb2__DOT__output_stream[110]),8);
    bufp->fullCData(oldp+119,(vlSelfRef.tb2__DOT__output_stream[111]),8);
    bufp->fullCData(oldp+120,(vlSelfRef.tb2__DOT__output_stream[112]),8);
    bufp->fullCData(oldp+121,(vlSelfRef.tb2__DOT__output_stream[113]),8);
    bufp->fullCData(oldp+122,(vlSelfRef.tb2__DOT__output_stream[114]),8);
    bufp->fullCData(oldp+123,(vlSelfRef.tb2__DOT__output_stream[115]),8);
    bufp->fullCData(oldp+124,(vlSelfRef.tb2__DOT__output_stream[116]),8);
    bufp->fullCData(oldp+125,(vlSelfRef.tb2__DOT__output_stream[117]),8);
    bufp->fullCData(oldp+126,(vlSelfRef.tb2__DOT__output_stream[118]),8);
    bufp->fullCData(oldp+127,(vlSelfRef.tb2__DOT__output_stream[119]),8);
    bufp->fullCData(oldp+128,(vlSelfRef.tb2__DOT__output_stream[120]),8);
    bufp->fullCData(oldp+129,(vlSelfRef.tb2__DOT__output_stream[121]),8);
    bufp->fullCData(oldp+130,(vlSelfRef.tb2__DOT__output_stream[122]),8);
    bufp->fullCData(oldp+131,(vlSelfRef.tb2__DOT__output_stream[123]),8);
    bufp->fullCData(oldp+132,(vlSelfRef.tb2__DOT__output_stream[124]),8);
    bufp->fullCData(oldp+133,(vlSelfRef.tb2__DOT__output_stream[125]),8);
    bufp->fullCData(oldp+134,(vlSelfRef.tb2__DOT__output_stream[126]),8);
    bufp->fullCData(oldp+135,(vlSelfRef.tb2__DOT__output_stream[127]),8);
    bufp->fullCData(oldp+136,(vlSelfRef.tb2__DOT__output_stream[128]),8);
    bufp->fullCData(oldp+137,(vlSelfRef.tb2__DOT__output_stream[129]),8);
    bufp->fullCData(oldp+138,(vlSelfRef.tb2__DOT__output_stream[130]),8);
    bufp->fullCData(oldp+139,(vlSelfRef.tb2__DOT__output_stream[131]),8);
    bufp->fullCData(oldp+140,(vlSelfRef.tb2__DOT__output_stream[132]),8);
    bufp->fullCData(oldp+141,(vlSelfRef.tb2__DOT__output_stream[133]),8);
    bufp->fullCData(oldp+142,(vlSelfRef.tb2__DOT__output_stream[134]),8);
    bufp->fullCData(oldp+143,(vlSelfRef.tb2__DOT__output_stream[135]),8);
    bufp->fullCData(oldp+144,(vlSelfRef.tb2__DOT__output_stream[136]),8);
    bufp->fullCData(oldp+145,(vlSelfRef.tb2__DOT__output_stream[137]),8);
    bufp->fullCData(oldp+146,(vlSelfRef.tb2__DOT__output_stream[138]),8);
    bufp->fullCData(oldp+147,(vlSelfRef.tb2__DOT__output_stream[139]),8);
    bufp->fullCData(oldp+148,(vlSelfRef.tb2__DOT__output_stream[140]),8);
    bufp->fullCData(oldp+149,(vlSelfRef.tb2__DOT__output_stream[141]),8);
    bufp->fullCData(oldp+150,(vlSelfRef.tb2__DOT__output_stream[142]),8);
    bufp->fullCData(oldp+151,(vlSelfRef.tb2__DOT__output_stream[143]),8);
    bufp->fullCData(oldp+152,(vlSelfRef.tb2__DOT__output_stream[144]),8);
    bufp->fullCData(oldp+153,(vlSelfRef.tb2__DOT__output_stream[145]),8);
    bufp->fullCData(oldp+154,(vlSelfRef.tb2__DOT__output_stream[146]),8);
    bufp->fullCData(oldp+155,(vlSelfRef.tb2__DOT__output_stream[147]),8);
    bufp->fullCData(oldp+156,(vlSelfRef.tb2__DOT__output_stream[148]),8);
    bufp->fullCData(oldp+157,(vlSelfRef.tb2__DOT__output_stream[149]),8);
    bufp->fullCData(oldp+158,(vlSelfRef.tb2__DOT__output_stream[150]),8);
    bufp->fullCData(oldp+159,(vlSelfRef.tb2__DOT__output_stream[151]),8);
    bufp->fullCData(oldp+160,(vlSelfRef.tb2__DOT__output_stream[152]),8);
    bufp->fullCData(oldp+161,(vlSelfRef.tb2__DOT__output_stream[153]),8);
    bufp->fullCData(oldp+162,(vlSelfRef.tb2__DOT__output_stream[154]),8);
    bufp->fullCData(oldp+163,(vlSelfRef.tb2__DOT__output_stream[155]),8);
    bufp->fullCData(oldp+164,(vlSelfRef.tb2__DOT__output_stream[156]),8);
    bufp->fullCData(oldp+165,(vlSelfRef.tb2__DOT__output_stream[157]),8);
    bufp->fullCData(oldp+166,(vlSelfRef.tb2__DOT__output_stream[158]),8);
    bufp->fullCData(oldp+167,(vlSelfRef.tb2__DOT__output_stream[159]),8);
    bufp->fullCData(oldp+168,(vlSelfRef.tb2__DOT__output_stream[160]),8);
    bufp->fullCData(oldp+169,(vlSelfRef.tb2__DOT__output_stream[161]),8);
    bufp->fullCData(oldp+170,(vlSelfRef.tb2__DOT__output_stream[162]),8);
    bufp->fullCData(oldp+171,(vlSelfRef.tb2__DOT__output_stream[163]),8);
    bufp->fullCData(oldp+172,(vlSelfRef.tb2__DOT__output_stream[164]),8);
    bufp->fullCData(oldp+173,(vlSelfRef.tb2__DOT__output_stream[165]),8);
    bufp->fullCData(oldp+174,(vlSelfRef.tb2__DOT__output_stream[166]),8);
    bufp->fullCData(oldp+175,(vlSelfRef.tb2__DOT__output_stream[167]),8);
    bufp->fullCData(oldp+176,(vlSelfRef.tb2__DOT__output_stream[168]),8);
    bufp->fullCData(oldp+177,(vlSelfRef.tb2__DOT__output_stream[169]),8);
    bufp->fullCData(oldp+178,(vlSelfRef.tb2__DOT__output_stream[170]),8);
    bufp->fullCData(oldp+179,(vlSelfRef.tb2__DOT__output_stream[171]),8);
    bufp->fullCData(oldp+180,(vlSelfRef.tb2__DOT__output_stream[172]),8);
    bufp->fullCData(oldp+181,(vlSelfRef.tb2__DOT__output_stream[173]),8);
    bufp->fullCData(oldp+182,(vlSelfRef.tb2__DOT__output_stream[174]),8);
    bufp->fullCData(oldp+183,(vlSelfRef.tb2__DOT__output_stream[175]),8);
    bufp->fullCData(oldp+184,(vlSelfRef.tb2__DOT__output_stream[176]),8);
    bufp->fullCData(oldp+185,(vlSelfRef.tb2__DOT__output_stream[177]),8);
    bufp->fullCData(oldp+186,(vlSelfRef.tb2__DOT__output_stream[178]),8);
    bufp->fullCData(oldp+187,(vlSelfRef.tb2__DOT__output_stream[179]),8);
    bufp->fullCData(oldp+188,(vlSelfRef.tb2__DOT__output_stream[180]),8);
    bufp->fullCData(oldp+189,(vlSelfRef.tb2__DOT__output_stream[181]),8);
    bufp->fullCData(oldp+190,(vlSelfRef.tb2__DOT__output_stream[182]),8);
    bufp->fullCData(oldp+191,(vlSelfRef.tb2__DOT__output_stream[183]),8);
    bufp->fullCData(oldp+192,(vlSelfRef.tb2__DOT__output_stream[184]),8);
    bufp->fullCData(oldp+193,(vlSelfRef.tb2__DOT__output_stream[185]),8);
    bufp->fullCData(oldp+194,(vlSelfRef.tb2__DOT__output_stream[186]),8);
    bufp->fullCData(oldp+195,(vlSelfRef.tb2__DOT__output_stream[187]),8);
    bufp->fullCData(oldp+196,(vlSelfRef.tb2__DOT__output_stream[188]),8);
    bufp->fullCData(oldp+197,(vlSelfRef.tb2__DOT__output_stream[189]),8);
    bufp->fullCData(oldp+198,(vlSelfRef.tb2__DOT__output_stream[190]),8);
    bufp->fullCData(oldp+199,(vlSelfRef.tb2__DOT__output_stream[191]),8);
    bufp->fullCData(oldp+200,(vlSelfRef.tb2__DOT__output_stream[192]),8);
    bufp->fullCData(oldp+201,(vlSelfRef.tb2__DOT__output_stream[193]),8);
    bufp->fullCData(oldp+202,(vlSelfRef.tb2__DOT__output_stream[194]),8);
    bufp->fullCData(oldp+203,(vlSelfRef.tb2__DOT__output_stream[195]),8);
    bufp->fullCData(oldp+204,(vlSelfRef.tb2__DOT__output_stream[196]),8);
    bufp->fullCData(oldp+205,(vlSelfRef.tb2__DOT__output_stream[197]),8);
    bufp->fullCData(oldp+206,(vlSelfRef.tb2__DOT__output_stream[198]),8);
    bufp->fullCData(oldp+207,(vlSelfRef.tb2__DOT__output_stream[199]),8);
    bufp->fullCData(oldp+208,(vlSelfRef.tb2__DOT__output_stream[200]),8);
    bufp->fullCData(oldp+209,(vlSelfRef.tb2__DOT__output_stream[201]),8);
    bufp->fullCData(oldp+210,(vlSelfRef.tb2__DOT__output_stream[202]),8);
    bufp->fullCData(oldp+211,(vlSelfRef.tb2__DOT__output_stream[203]),8);
    bufp->fullCData(oldp+212,(vlSelfRef.tb2__DOT__output_stream[204]),8);
    bufp->fullCData(oldp+213,(vlSelfRef.tb2__DOT__output_stream[205]),8);
    bufp->fullCData(oldp+214,(vlSelfRef.tb2__DOT__output_stream[206]),8);
    bufp->fullCData(oldp+215,(vlSelfRef.tb2__DOT__output_stream[207]),8);
    bufp->fullCData(oldp+216,(vlSelfRef.tb2__DOT__output_stream[208]),8);
    bufp->fullCData(oldp+217,(vlSelfRef.tb2__DOT__output_stream[209]),8);
    bufp->fullCData(oldp+218,(vlSelfRef.tb2__DOT__output_stream[210]),8);
    bufp->fullCData(oldp+219,(vlSelfRef.tb2__DOT__output_stream[211]),8);
    bufp->fullCData(oldp+220,(vlSelfRef.tb2__DOT__output_stream[212]),8);
    bufp->fullCData(oldp+221,(vlSelfRef.tb2__DOT__output_stream[213]),8);
    bufp->fullCData(oldp+222,(vlSelfRef.tb2__DOT__output_stream[214]),8);
    bufp->fullCData(oldp+223,(vlSelfRef.tb2__DOT__output_stream[215]),8);
    bufp->fullCData(oldp+224,(vlSelfRef.tb2__DOT__output_stream[216]),8);
    bufp->fullCData(oldp+225,(vlSelfRef.tb2__DOT__output_stream[217]),8);
    bufp->fullCData(oldp+226,(vlSelfRef.tb2__DOT__output_stream[218]),8);
    bufp->fullCData(oldp+227,(vlSelfRef.tb2__DOT__output_stream[219]),8);
    bufp->fullCData(oldp+228,(vlSelfRef.tb2__DOT__output_stream[220]),8);
    bufp->fullCData(oldp+229,(vlSelfRef.tb2__DOT__output_stream[221]),8);
    bufp->fullCData(oldp+230,(vlSelfRef.tb2__DOT__output_stream[222]),8);
    bufp->fullCData(oldp+231,(vlSelfRef.tb2__DOT__output_stream[223]),8);
    bufp->fullCData(oldp+232,(vlSelfRef.tb2__DOT__output_stream[224]),8);
    bufp->fullCData(oldp+233,(vlSelfRef.tb2__DOT__output_stream[225]),8);
    bufp->fullCData(oldp+234,(vlSelfRef.tb2__DOT__output_stream[226]),8);
    bufp->fullCData(oldp+235,(vlSelfRef.tb2__DOT__output_stream[227]),8);
    bufp->fullCData(oldp+236,(vlSelfRef.tb2__DOT__output_stream[228]),8);
    bufp->fullCData(oldp+237,(vlSelfRef.tb2__DOT__output_stream[229]),8);
    bufp->fullCData(oldp+238,(vlSelfRef.tb2__DOT__output_stream[230]),8);
    bufp->fullCData(oldp+239,(vlSelfRef.tb2__DOT__output_stream[231]),8);
    bufp->fullCData(oldp+240,(vlSelfRef.tb2__DOT__output_stream[232]),8);
    bufp->fullCData(oldp+241,(vlSelfRef.tb2__DOT__output_stream[233]),8);
    bufp->fullCData(oldp+242,(vlSelfRef.tb2__DOT__output_stream[234]),8);
    bufp->fullCData(oldp+243,(vlSelfRef.tb2__DOT__output_stream[235]),8);
    bufp->fullCData(oldp+244,(vlSelfRef.tb2__DOT__output_stream[236]),8);
    bufp->fullCData(oldp+245,(vlSelfRef.tb2__DOT__output_stream[237]),8);
    bufp->fullCData(oldp+246,(vlSelfRef.tb2__DOT__output_stream[238]),8);
    bufp->fullCData(oldp+247,(vlSelfRef.tb2__DOT__output_stream[239]),8);
    bufp->fullCData(oldp+248,(vlSelfRef.tb2__DOT__output_stream[240]),8);
    bufp->fullCData(oldp+249,(vlSelfRef.tb2__DOT__output_stream[241]),8);
    bufp->fullCData(oldp+250,(vlSelfRef.tb2__DOT__output_stream[242]),8);
    bufp->fullCData(oldp+251,(vlSelfRef.tb2__DOT__output_stream[243]),8);
    bufp->fullCData(oldp+252,(vlSelfRef.tb2__DOT__output_stream[244]),8);
    bufp->fullCData(oldp+253,(vlSelfRef.tb2__DOT__output_stream[245]),8);
    bufp->fullCData(oldp+254,(vlSelfRef.tb2__DOT__output_stream[246]),8);
    bufp->fullCData(oldp+255,(vlSelfRef.tb2__DOT__output_stream[247]),8);
    bufp->fullCData(oldp+256,(vlSelfRef.tb2__DOT__output_stream[248]),8);
    bufp->fullCData(oldp+257,(vlSelfRef.tb2__DOT__output_stream[249]),8);
    bufp->fullCData(oldp+258,(vlSelfRef.tb2__DOT__output_stream[250]),8);
    bufp->fullCData(oldp+259,(vlSelfRef.tb2__DOT__output_stream[251]),8);
    bufp->fullCData(oldp+260,(vlSelfRef.tb2__DOT__output_stream[252]),8);
    bufp->fullCData(oldp+261,(vlSelfRef.tb2__DOT__output_stream[253]),8);
    bufp->fullCData(oldp+262,(vlSelfRef.tb2__DOT__output_stream[254]),8);
    bufp->fullCData(oldp+263,(vlSelfRef.tb2__DOT__output_stream[255]),8);
    bufp->fullCData(oldp+264,(vlSelfRef.tb2__DOT__output_stream[256]),8);
    bufp->fullCData(oldp+265,(vlSelfRef.tb2__DOT__output_stream[257]),8);
    bufp->fullCData(oldp+266,(vlSelfRef.tb2__DOT__output_stream[258]),8);
    bufp->fullCData(oldp+267,(vlSelfRef.tb2__DOT__output_stream[259]),8);
    bufp->fullCData(oldp+268,(vlSelfRef.tb2__DOT__output_stream[260]),8);
    bufp->fullCData(oldp+269,(vlSelfRef.tb2__DOT__output_stream[261]),8);
    bufp->fullCData(oldp+270,(vlSelfRef.tb2__DOT__output_stream[262]),8);
    bufp->fullCData(oldp+271,(vlSelfRef.tb2__DOT__output_stream[263]),8);
    bufp->fullCData(oldp+272,(vlSelfRef.tb2__DOT__output_stream[264]),8);
    bufp->fullCData(oldp+273,(vlSelfRef.tb2__DOT__output_stream[265]),8);
    bufp->fullCData(oldp+274,(vlSelfRef.tb2__DOT__output_stream[266]),8);
    bufp->fullCData(oldp+275,(vlSelfRef.tb2__DOT__output_stream[267]),8);
    bufp->fullCData(oldp+276,(vlSelfRef.tb2__DOT__output_stream[268]),8);
    bufp->fullCData(oldp+277,(vlSelfRef.tb2__DOT__output_stream[269]),8);
    bufp->fullCData(oldp+278,(vlSelfRef.tb2__DOT__output_stream[270]),8);
    bufp->fullCData(oldp+279,(vlSelfRef.tb2__DOT__output_stream[271]),8);
    bufp->fullCData(oldp+280,(vlSelfRef.tb2__DOT__output_stream[272]),8);
    bufp->fullCData(oldp+281,(vlSelfRef.tb2__DOT__output_stream[273]),8);
    bufp->fullCData(oldp+282,(vlSelfRef.tb2__DOT__output_stream[274]),8);
    bufp->fullCData(oldp+283,(vlSelfRef.tb2__DOT__output_stream[275]),8);
    bufp->fullCData(oldp+284,(vlSelfRef.tb2__DOT__output_stream[276]),8);
    bufp->fullCData(oldp+285,(vlSelfRef.tb2__DOT__output_stream[277]),8);
    bufp->fullCData(oldp+286,(vlSelfRef.tb2__DOT__output_stream[278]),8);
    bufp->fullCData(oldp+287,(vlSelfRef.tb2__DOT__output_stream[279]),8);
    bufp->fullCData(oldp+288,(vlSelfRef.tb2__DOT__output_stream[280]),8);
    bufp->fullCData(oldp+289,(vlSelfRef.tb2__DOT__output_stream[281]),8);
    bufp->fullCData(oldp+290,(vlSelfRef.tb2__DOT__output_stream[282]),8);
    bufp->fullCData(oldp+291,(vlSelfRef.tb2__DOT__output_stream[283]),8);
    bufp->fullCData(oldp+292,(vlSelfRef.tb2__DOT__output_stream[284]),8);
    bufp->fullCData(oldp+293,(vlSelfRef.tb2__DOT__output_stream[285]),8);
    bufp->fullCData(oldp+294,(vlSelfRef.tb2__DOT__output_stream[286]),8);
    bufp->fullCData(oldp+295,(vlSelfRef.tb2__DOT__output_stream[287]),8);
    bufp->fullCData(oldp+296,(vlSelfRef.tb2__DOT__output_stream[288]),8);
    bufp->fullCData(oldp+297,(vlSelfRef.tb2__DOT__output_stream[289]),8);
    bufp->fullCData(oldp+298,(vlSelfRef.tb2__DOT__output_stream[290]),8);
    bufp->fullCData(oldp+299,(vlSelfRef.tb2__DOT__output_stream[291]),8);
    bufp->fullCData(oldp+300,(vlSelfRef.tb2__DOT__output_stream[292]),8);
    bufp->fullCData(oldp+301,(vlSelfRef.tb2__DOT__output_stream[293]),8);
    bufp->fullCData(oldp+302,(vlSelfRef.tb2__DOT__output_stream[294]),8);
    bufp->fullCData(oldp+303,(vlSelfRef.tb2__DOT__output_stream[295]),8);
    bufp->fullCData(oldp+304,(vlSelfRef.tb2__DOT__output_stream[296]),8);
    bufp->fullCData(oldp+305,(vlSelfRef.tb2__DOT__output_stream[297]),8);
    bufp->fullCData(oldp+306,(vlSelfRef.tb2__DOT__output_stream[298]),8);
    bufp->fullCData(oldp+307,(vlSelfRef.tb2__DOT__output_stream[299]),8);
    bufp->fullCData(oldp+308,(vlSelfRef.tb2__DOT__output_stream[300]),8);
    bufp->fullCData(oldp+309,(vlSelfRef.tb2__DOT__output_stream[301]),8);
    bufp->fullCData(oldp+310,(vlSelfRef.tb2__DOT__output_stream[302]),8);
    bufp->fullCData(oldp+311,(vlSelfRef.tb2__DOT__output_stream[303]),8);
    bufp->fullCData(oldp+312,(vlSelfRef.tb2__DOT__output_stream[304]),8);
    bufp->fullCData(oldp+313,(vlSelfRef.tb2__DOT__output_stream[305]),8);
    bufp->fullCData(oldp+314,(vlSelfRef.tb2__DOT__output_stream[306]),8);
    bufp->fullCData(oldp+315,(vlSelfRef.tb2__DOT__output_stream[307]),8);
    bufp->fullCData(oldp+316,(vlSelfRef.tb2__DOT__output_stream[308]),8);
    bufp->fullCData(oldp+317,(vlSelfRef.tb2__DOT__output_stream[309]),8);
    bufp->fullCData(oldp+318,(vlSelfRef.tb2__DOT__output_stream[310]),8);
    bufp->fullCData(oldp+319,(vlSelfRef.tb2__DOT__output_stream[311]),8);
    bufp->fullCData(oldp+320,(vlSelfRef.tb2__DOT__output_stream[312]),8);
    bufp->fullCData(oldp+321,(vlSelfRef.tb2__DOT__output_stream[313]),8);
    bufp->fullCData(oldp+322,(vlSelfRef.tb2__DOT__output_stream[314]),8);
    bufp->fullCData(oldp+323,(vlSelfRef.tb2__DOT__output_stream[315]),8);
    bufp->fullCData(oldp+324,(vlSelfRef.tb2__DOT__output_stream[316]),8);
    bufp->fullCData(oldp+325,(vlSelfRef.tb2__DOT__output_stream[317]),8);
    bufp->fullCData(oldp+326,(vlSelfRef.tb2__DOT__output_stream[318]),8);
    bufp->fullCData(oldp+327,(vlSelfRef.tb2__DOT__output_stream[319]),8);
    bufp->fullSData(oldp+328,(vlSelfRef.tb2__DOT__rgbstack[0]),12);
    bufp->fullSData(oldp+329,(vlSelfRef.tb2__DOT__rgbstack[1]),12);
    bufp->fullSData(oldp+330,(vlSelfRef.tb2__DOT__rgbstack[2]),12);
    bufp->fullSData(oldp+331,(vlSelfRef.tb2__DOT__rgbstack[3]),12);
    bufp->fullSData(oldp+332,(vlSelfRef.tb2__DOT__rgbstack[4]),12);
    bufp->fullSData(oldp+333,(vlSelfRef.tb2__DOT__rgbstack[5]),12);
    bufp->fullSData(oldp+334,(vlSelfRef.tb2__DOT__rgbstack[6]),12);
    bufp->fullSData(oldp+335,(vlSelfRef.tb2__DOT__rgbstack[7]),12);
    bufp->fullSData(oldp+336,(vlSelfRef.tb2__DOT__rgbstack[8]),12);
    bufp->fullSData(oldp+337,(vlSelfRef.tb2__DOT__rgbstack[9]),12);
    bufp->fullSData(oldp+338,(vlSelfRef.tb2__DOT__rgbstack[10]),12);
    bufp->fullSData(oldp+339,(vlSelfRef.tb2__DOT__rgbstack[11]),12);
    bufp->fullSData(oldp+340,(vlSelfRef.tb2__DOT__rgbstack[12]),12);
    bufp->fullSData(oldp+341,(vlSelfRef.tb2__DOT__rgbstack[13]),12);
    bufp->fullSData(oldp+342,(vlSelfRef.tb2__DOT__rgbstack[14]),12);
    bufp->fullSData(oldp+343,(vlSelfRef.tb2__DOT__rgbstack[15]),12);
    bufp->fullSData(oldp+344,(vlSelfRef.tb2__DOT__rgbstack[16]),12);
    bufp->fullSData(oldp+345,(vlSelfRef.tb2__DOT__rgbstack[17]),12);
    bufp->fullSData(oldp+346,(vlSelfRef.tb2__DOT__rgbstack[18]),12);
    bufp->fullSData(oldp+347,(vlSelfRef.tb2__DOT__rgbstack[19]),12);
    bufp->fullSData(oldp+348,(vlSelfRef.tb2__DOT__rgbstack[20]),12);
    bufp->fullSData(oldp+349,(vlSelfRef.tb2__DOT__rgbstack[21]),12);
    bufp->fullSData(oldp+350,(vlSelfRef.tb2__DOT__rgbstack[22]),12);
    bufp->fullSData(oldp+351,(vlSelfRef.tb2__DOT__rgbstack[23]),12);
    bufp->fullSData(oldp+352,(vlSelfRef.tb2__DOT__rgbstack[24]),12);
    bufp->fullSData(oldp+353,(vlSelfRef.tb2__DOT__rgbstack[25]),12);
    bufp->fullSData(oldp+354,(vlSelfRef.tb2__DOT__rgbstack[26]),12);
    bufp->fullSData(oldp+355,(vlSelfRef.tb2__DOT__rgbstack[27]),12);
    bufp->fullSData(oldp+356,(vlSelfRef.tb2__DOT__rgbstack[28]),12);
    bufp->fullSData(oldp+357,(vlSelfRef.tb2__DOT__rgbstack[29]),12);
    bufp->fullSData(oldp+358,(vlSelfRef.tb2__DOT__rgbstack[30]),12);
    bufp->fullSData(oldp+359,(vlSelfRef.tb2__DOT__rgbstack[31]),12);
    bufp->fullSData(oldp+360,(vlSelfRef.tb2__DOT__rgbstack[32]),12);
    bufp->fullSData(oldp+361,(vlSelfRef.tb2__DOT__rgbstack[33]),12);
    bufp->fullSData(oldp+362,(vlSelfRef.tb2__DOT__rgbstack[34]),12);
    bufp->fullSData(oldp+363,(vlSelfRef.tb2__DOT__rgbstack[35]),12);
    bufp->fullSData(oldp+364,(vlSelfRef.tb2__DOT__rgbstack[36]),12);
    bufp->fullSData(oldp+365,(vlSelfRef.tb2__DOT__rgbstack[37]),12);
    bufp->fullSData(oldp+366,(vlSelfRef.tb2__DOT__rgbstack[38]),12);
    bufp->fullSData(oldp+367,(vlSelfRef.tb2__DOT__rgbstack[39]),12);
    bufp->fullSData(oldp+368,(vlSelfRef.tb2__DOT__rgbstack[40]),12);
    bufp->fullSData(oldp+369,(vlSelfRef.tb2__DOT__rgbstack[41]),12);
    bufp->fullSData(oldp+370,(vlSelfRef.tb2__DOT__rgbstack[42]),12);
    bufp->fullSData(oldp+371,(vlSelfRef.tb2__DOT__rgbstack[43]),12);
    bufp->fullSData(oldp+372,(vlSelfRef.tb2__DOT__rgbstack[44]),12);
    bufp->fullSData(oldp+373,(vlSelfRef.tb2__DOT__rgbstack[45]),12);
    bufp->fullSData(oldp+374,(vlSelfRef.tb2__DOT__rgbstack[46]),12);
    bufp->fullSData(oldp+375,(vlSelfRef.tb2__DOT__rgbstack[47]),12);
    bufp->fullSData(oldp+376,(vlSelfRef.tb2__DOT__rgbstack[48]),12);
    bufp->fullSData(oldp+377,(vlSelfRef.tb2__DOT__rgbstack[49]),12);
    bufp->fullSData(oldp+378,(vlSelfRef.tb2__DOT__rgbstack[50]),12);
    bufp->fullSData(oldp+379,(vlSelfRef.tb2__DOT__rgbstack[51]),12);
    bufp->fullSData(oldp+380,(vlSelfRef.tb2__DOT__rgbstack[52]),12);
    bufp->fullSData(oldp+381,(vlSelfRef.tb2__DOT__rgbstack[53]),12);
    bufp->fullSData(oldp+382,(vlSelfRef.tb2__DOT__rgbstack[54]),12);
    bufp->fullSData(oldp+383,(vlSelfRef.tb2__DOT__rgbstack[55]),12);
    bufp->fullSData(oldp+384,(vlSelfRef.tb2__DOT__rgbstack[56]),12);
    bufp->fullSData(oldp+385,(vlSelfRef.tb2__DOT__rgbstack[57]),12);
    bufp->fullSData(oldp+386,(vlSelfRef.tb2__DOT__rgbstack[58]),12);
    bufp->fullSData(oldp+387,(vlSelfRef.tb2__DOT__rgbstack[59]),12);
    bufp->fullSData(oldp+388,(vlSelfRef.tb2__DOT__rgbstack[60]),12);
    bufp->fullSData(oldp+389,(vlSelfRef.tb2__DOT__rgbstack[61]),12);
    bufp->fullSData(oldp+390,(vlSelfRef.tb2__DOT__rgbstack[62]),12);
    bufp->fullSData(oldp+391,(vlSelfRef.tb2__DOT__rgbstack[63]),12);
    bufp->fullBit(oldp+392,(vlSelfRef.tb2__DOT__capped));
    bufp->fullCData(oldp+393,(vlSelfRef.tb2__DOT__enc__DOT__stream[0]),8);
    bufp->fullCData(oldp+394,(vlSelfRef.tb2__DOT__enc__DOT__stream[1]),8);
    bufp->fullCData(oldp+395,(vlSelfRef.tb2__DOT__enc__DOT__stream[2]),8);
    bufp->fullCData(oldp+396,(vlSelfRef.tb2__DOT__enc__DOT__stream[3]),8);
    bufp->fullCData(oldp+397,(vlSelfRef.tb2__DOT__enc__DOT__stream[4]),8);
    bufp->fullCData(oldp+398,(vlSelfRef.tb2__DOT__enc__DOT__stream[5]),8);
    bufp->fullCData(oldp+399,(vlSelfRef.tb2__DOT__enc__DOT__stream[6]),8);
    bufp->fullCData(oldp+400,(vlSelfRef.tb2__DOT__enc__DOT__stream[7]),8);
    bufp->fullCData(oldp+401,(vlSelfRef.tb2__DOT__enc__DOT__stream[8]),8);
    bufp->fullCData(oldp+402,(vlSelfRef.tb2__DOT__enc__DOT__stream[9]),8);
    bufp->fullCData(oldp+403,(vlSelfRef.tb2__DOT__enc__DOT__stream[10]),8);
    bufp->fullCData(oldp+404,(vlSelfRef.tb2__DOT__enc__DOT__stream[11]),8);
    bufp->fullCData(oldp+405,(vlSelfRef.tb2__DOT__enc__DOT__stream[12]),8);
    bufp->fullCData(oldp+406,(vlSelfRef.tb2__DOT__enc__DOT__stream[13]),8);
    bufp->fullCData(oldp+407,(vlSelfRef.tb2__DOT__enc__DOT__stream[14]),8);
    bufp->fullCData(oldp+408,(vlSelfRef.tb2__DOT__enc__DOT__stream[15]),8);
    bufp->fullCData(oldp+409,(vlSelfRef.tb2__DOT__enc__DOT__stream[16]),8);
    bufp->fullCData(oldp+410,(vlSelfRef.tb2__DOT__enc__DOT__stream[17]),8);
    bufp->fullCData(oldp+411,(vlSelfRef.tb2__DOT__enc__DOT__stream[18]),8);
    bufp->fullCData(oldp+412,(vlSelfRef.tb2__DOT__enc__DOT__stream[19]),8);
    bufp->fullCData(oldp+413,(vlSelfRef.tb2__DOT__enc__DOT__stream[20]),8);
    bufp->fullCData(oldp+414,(vlSelfRef.tb2__DOT__enc__DOT__stream[21]),8);
    bufp->fullCData(oldp+415,(vlSelfRef.tb2__DOT__enc__DOT__stream[22]),8);
    bufp->fullCData(oldp+416,(vlSelfRef.tb2__DOT__enc__DOT__stream[23]),8);
    bufp->fullCData(oldp+417,(vlSelfRef.tb2__DOT__enc__DOT__stream[24]),8);
    bufp->fullCData(oldp+418,(vlSelfRef.tb2__DOT__enc__DOT__stream[25]),8);
    bufp->fullCData(oldp+419,(vlSelfRef.tb2__DOT__enc__DOT__stream[26]),8);
    bufp->fullCData(oldp+420,(vlSelfRef.tb2__DOT__enc__DOT__stream[27]),8);
    bufp->fullCData(oldp+421,(vlSelfRef.tb2__DOT__enc__DOT__stream[28]),8);
    bufp->fullCData(oldp+422,(vlSelfRef.tb2__DOT__enc__DOT__stream[29]),8);
    bufp->fullCData(oldp+423,(vlSelfRef.tb2__DOT__enc__DOT__stream[30]),8);
    bufp->fullCData(oldp+424,(vlSelfRef.tb2__DOT__enc__DOT__stream[31]),8);
    bufp->fullCData(oldp+425,(vlSelfRef.tb2__DOT__enc__DOT__stream[32]),8);
    bufp->fullCData(oldp+426,(vlSelfRef.tb2__DOT__enc__DOT__stream[33]),8);
    bufp->fullCData(oldp+427,(vlSelfRef.tb2__DOT__enc__DOT__stream[34]),8);
    bufp->fullCData(oldp+428,(vlSelfRef.tb2__DOT__enc__DOT__stream[35]),8);
    bufp->fullCData(oldp+429,(vlSelfRef.tb2__DOT__enc__DOT__stream[36]),8);
    bufp->fullCData(oldp+430,(vlSelfRef.tb2__DOT__enc__DOT__stream[37]),8);
    bufp->fullCData(oldp+431,(vlSelfRef.tb2__DOT__enc__DOT__stream[38]),8);
    bufp->fullCData(oldp+432,(vlSelfRef.tb2__DOT__enc__DOT__stream[39]),8);
    bufp->fullCData(oldp+433,(vlSelfRef.tb2__DOT__enc__DOT__stream[40]),8);
    bufp->fullCData(oldp+434,(vlSelfRef.tb2__DOT__enc__DOT__stream[41]),8);
    bufp->fullCData(oldp+435,(vlSelfRef.tb2__DOT__enc__DOT__stream[42]),8);
    bufp->fullCData(oldp+436,(vlSelfRef.tb2__DOT__enc__DOT__stream[43]),8);
    bufp->fullCData(oldp+437,(vlSelfRef.tb2__DOT__enc__DOT__stream[44]),8);
    bufp->fullCData(oldp+438,(vlSelfRef.tb2__DOT__enc__DOT__stream[45]),8);
    bufp->fullCData(oldp+439,(vlSelfRef.tb2__DOT__enc__DOT__stream[46]),8);
    bufp->fullCData(oldp+440,(vlSelfRef.tb2__DOT__enc__DOT__stream[47]),8);
    bufp->fullCData(oldp+441,(vlSelfRef.tb2__DOT__enc__DOT__stream[48]),8);
    bufp->fullCData(oldp+442,(vlSelfRef.tb2__DOT__enc__DOT__stream[49]),8);
    bufp->fullCData(oldp+443,(vlSelfRef.tb2__DOT__enc__DOT__stream[50]),8);
    bufp->fullCData(oldp+444,(vlSelfRef.tb2__DOT__enc__DOT__stream[51]),8);
    bufp->fullCData(oldp+445,(vlSelfRef.tb2__DOT__enc__DOT__stream[52]),8);
    bufp->fullCData(oldp+446,(vlSelfRef.tb2__DOT__enc__DOT__stream[53]),8);
    bufp->fullCData(oldp+447,(vlSelfRef.tb2__DOT__enc__DOT__stream[54]),8);
    bufp->fullCData(oldp+448,(vlSelfRef.tb2__DOT__enc__DOT__stream[55]),8);
    bufp->fullCData(oldp+449,(vlSelfRef.tb2__DOT__enc__DOT__stream[56]),8);
    bufp->fullCData(oldp+450,(vlSelfRef.tb2__DOT__enc__DOT__stream[57]),8);
    bufp->fullCData(oldp+451,(vlSelfRef.tb2__DOT__enc__DOT__stream[58]),8);
    bufp->fullCData(oldp+452,(vlSelfRef.tb2__DOT__enc__DOT__stream[59]),8);
    bufp->fullCData(oldp+453,(vlSelfRef.tb2__DOT__enc__DOT__stream[60]),8);
    bufp->fullCData(oldp+454,(vlSelfRef.tb2__DOT__enc__DOT__stream[61]),8);
    bufp->fullCData(oldp+455,(vlSelfRef.tb2__DOT__enc__DOT__stream[62]),8);
    bufp->fullCData(oldp+456,(vlSelfRef.tb2__DOT__enc__DOT__stream[63]),8);
    bufp->fullCData(oldp+457,(vlSelfRef.tb2__DOT__enc__DOT__stream[64]),8);
    bufp->fullCData(oldp+458,(vlSelfRef.tb2__DOT__enc__DOT__stream[65]),8);
    bufp->fullCData(oldp+459,(vlSelfRef.tb2__DOT__enc__DOT__stream[66]),8);
    bufp->fullCData(oldp+460,(vlSelfRef.tb2__DOT__enc__DOT__stream[67]),8);
    bufp->fullCData(oldp+461,(vlSelfRef.tb2__DOT__enc__DOT__stream[68]),8);
    bufp->fullCData(oldp+462,(vlSelfRef.tb2__DOT__enc__DOT__stream[69]),8);
    bufp->fullCData(oldp+463,(vlSelfRef.tb2__DOT__enc__DOT__stream[70]),8);
    bufp->fullCData(oldp+464,(vlSelfRef.tb2__DOT__enc__DOT__stream[71]),8);
    bufp->fullCData(oldp+465,(vlSelfRef.tb2__DOT__enc__DOT__stream[72]),8);
    bufp->fullCData(oldp+466,(vlSelfRef.tb2__DOT__enc__DOT__stream[73]),8);
    bufp->fullCData(oldp+467,(vlSelfRef.tb2__DOT__enc__DOT__stream[74]),8);
    bufp->fullCData(oldp+468,(vlSelfRef.tb2__DOT__enc__DOT__stream[75]),8);
    bufp->fullCData(oldp+469,(vlSelfRef.tb2__DOT__enc__DOT__stream[76]),8);
    bufp->fullCData(oldp+470,(vlSelfRef.tb2__DOT__enc__DOT__stream[77]),8);
    bufp->fullCData(oldp+471,(vlSelfRef.tb2__DOT__enc__DOT__stream[78]),8);
    bufp->fullCData(oldp+472,(vlSelfRef.tb2__DOT__enc__DOT__stream[79]),8);
    bufp->fullCData(oldp+473,(vlSelfRef.tb2__DOT__enc__DOT__stream[80]),8);
    bufp->fullCData(oldp+474,(vlSelfRef.tb2__DOT__enc__DOT__stream[81]),8);
    bufp->fullCData(oldp+475,(vlSelfRef.tb2__DOT__enc__DOT__stream[82]),8);
    bufp->fullCData(oldp+476,(vlSelfRef.tb2__DOT__enc__DOT__stream[83]),8);
    bufp->fullCData(oldp+477,(vlSelfRef.tb2__DOT__enc__DOT__stream[84]),8);
    bufp->fullCData(oldp+478,(vlSelfRef.tb2__DOT__enc__DOT__stream[85]),8);
    bufp->fullCData(oldp+479,(vlSelfRef.tb2__DOT__enc__DOT__stream[86]),8);
    bufp->fullCData(oldp+480,(vlSelfRef.tb2__DOT__enc__DOT__stream[87]),8);
    bufp->fullCData(oldp+481,(vlSelfRef.tb2__DOT__enc__DOT__stream[88]),8);
    bufp->fullCData(oldp+482,(vlSelfRef.tb2__DOT__enc__DOT__stream[89]),8);
    bufp->fullCData(oldp+483,(vlSelfRef.tb2__DOT__enc__DOT__stream[90]),8);
    bufp->fullCData(oldp+484,(vlSelfRef.tb2__DOT__enc__DOT__stream[91]),8);
    bufp->fullCData(oldp+485,(vlSelfRef.tb2__DOT__enc__DOT__stream[92]),8);
    bufp->fullCData(oldp+486,(vlSelfRef.tb2__DOT__enc__DOT__stream[93]),8);
    bufp->fullCData(oldp+487,(vlSelfRef.tb2__DOT__enc__DOT__stream[94]),8);
    bufp->fullCData(oldp+488,(vlSelfRef.tb2__DOT__enc__DOT__stream[95]),8);
    bufp->fullCData(oldp+489,(vlSelfRef.tb2__DOT__enc__DOT__stream[96]),8);
    bufp->fullCData(oldp+490,(vlSelfRef.tb2__DOT__enc__DOT__stream[97]),8);
    bufp->fullCData(oldp+491,(vlSelfRef.tb2__DOT__enc__DOT__stream[98]),8);
    bufp->fullCData(oldp+492,(vlSelfRef.tb2__DOT__enc__DOT__stream[99]),8);
    bufp->fullCData(oldp+493,(vlSelfRef.tb2__DOT__enc__DOT__stream[100]),8);
    bufp->fullCData(oldp+494,(vlSelfRef.tb2__DOT__enc__DOT__stream[101]),8);
    bufp->fullCData(oldp+495,(vlSelfRef.tb2__DOT__enc__DOT__stream[102]),8);
    bufp->fullCData(oldp+496,(vlSelfRef.tb2__DOT__enc__DOT__stream[103]),8);
    bufp->fullCData(oldp+497,(vlSelfRef.tb2__DOT__enc__DOT__stream[104]),8);
    bufp->fullCData(oldp+498,(vlSelfRef.tb2__DOT__enc__DOT__stream[105]),8);
    bufp->fullCData(oldp+499,(vlSelfRef.tb2__DOT__enc__DOT__stream[106]),8);
    bufp->fullCData(oldp+500,(vlSelfRef.tb2__DOT__enc__DOT__stream[107]),8);
    bufp->fullCData(oldp+501,(vlSelfRef.tb2__DOT__enc__DOT__stream[108]),8);
    bufp->fullCData(oldp+502,(vlSelfRef.tb2__DOT__enc__DOT__stream[109]),8);
    bufp->fullCData(oldp+503,(vlSelfRef.tb2__DOT__enc__DOT__stream[110]),8);
    bufp->fullCData(oldp+504,(vlSelfRef.tb2__DOT__enc__DOT__stream[111]),8);
    bufp->fullCData(oldp+505,(vlSelfRef.tb2__DOT__enc__DOT__stream[112]),8);
    bufp->fullCData(oldp+506,(vlSelfRef.tb2__DOT__enc__DOT__stream[113]),8);
    bufp->fullCData(oldp+507,(vlSelfRef.tb2__DOT__enc__DOT__stream[114]),8);
    bufp->fullCData(oldp+508,(vlSelfRef.tb2__DOT__enc__DOT__stream[115]),8);
    bufp->fullCData(oldp+509,(vlSelfRef.tb2__DOT__enc__DOT__stream[116]),8);
    bufp->fullCData(oldp+510,(vlSelfRef.tb2__DOT__enc__DOT__stream[117]),8);
    bufp->fullCData(oldp+511,(vlSelfRef.tb2__DOT__enc__DOT__stream[118]),8);
    bufp->fullCData(oldp+512,(vlSelfRef.tb2__DOT__enc__DOT__stream[119]),8);
    bufp->fullCData(oldp+513,(vlSelfRef.tb2__DOT__enc__DOT__stream[120]),8);
    bufp->fullCData(oldp+514,(vlSelfRef.tb2__DOT__enc__DOT__stream[121]),8);
    bufp->fullCData(oldp+515,(vlSelfRef.tb2__DOT__enc__DOT__stream[122]),8);
    bufp->fullCData(oldp+516,(vlSelfRef.tb2__DOT__enc__DOT__stream[123]),8);
    bufp->fullCData(oldp+517,(vlSelfRef.tb2__DOT__enc__DOT__stream[124]),8);
    bufp->fullCData(oldp+518,(vlSelfRef.tb2__DOT__enc__DOT__stream[125]),8);
    bufp->fullCData(oldp+519,(vlSelfRef.tb2__DOT__enc__DOT__stream[126]),8);
    bufp->fullCData(oldp+520,(vlSelfRef.tb2__DOT__enc__DOT__stream[127]),8);
    bufp->fullCData(oldp+521,(vlSelfRef.tb2__DOT__enc__DOT__stream[128]),8);
    bufp->fullCData(oldp+522,(vlSelfRef.tb2__DOT__enc__DOT__stream[129]),8);
    bufp->fullCData(oldp+523,(vlSelfRef.tb2__DOT__enc__DOT__stream[130]),8);
    bufp->fullCData(oldp+524,(vlSelfRef.tb2__DOT__enc__DOT__stream[131]),8);
    bufp->fullCData(oldp+525,(vlSelfRef.tb2__DOT__enc__DOT__stream[132]),8);
    bufp->fullCData(oldp+526,(vlSelfRef.tb2__DOT__enc__DOT__stream[133]),8);
    bufp->fullCData(oldp+527,(vlSelfRef.tb2__DOT__enc__DOT__stream[134]),8);
    bufp->fullCData(oldp+528,(vlSelfRef.tb2__DOT__enc__DOT__stream[135]),8);
    bufp->fullCData(oldp+529,(vlSelfRef.tb2__DOT__enc__DOT__stream[136]),8);
    bufp->fullCData(oldp+530,(vlSelfRef.tb2__DOT__enc__DOT__stream[137]),8);
    bufp->fullCData(oldp+531,(vlSelfRef.tb2__DOT__enc__DOT__stream[138]),8);
    bufp->fullCData(oldp+532,(vlSelfRef.tb2__DOT__enc__DOT__stream[139]),8);
    bufp->fullCData(oldp+533,(vlSelfRef.tb2__DOT__enc__DOT__stream[140]),8);
    bufp->fullCData(oldp+534,(vlSelfRef.tb2__DOT__enc__DOT__stream[141]),8);
    bufp->fullCData(oldp+535,(vlSelfRef.tb2__DOT__enc__DOT__stream[142]),8);
    bufp->fullCData(oldp+536,(vlSelfRef.tb2__DOT__enc__DOT__stream[143]),8);
    bufp->fullCData(oldp+537,(vlSelfRef.tb2__DOT__enc__DOT__stream[144]),8);
    bufp->fullCData(oldp+538,(vlSelfRef.tb2__DOT__enc__DOT__stream[145]),8);
    bufp->fullCData(oldp+539,(vlSelfRef.tb2__DOT__enc__DOT__stream[146]),8);
    bufp->fullCData(oldp+540,(vlSelfRef.tb2__DOT__enc__DOT__stream[147]),8);
    bufp->fullCData(oldp+541,(vlSelfRef.tb2__DOT__enc__DOT__stream[148]),8);
    bufp->fullCData(oldp+542,(vlSelfRef.tb2__DOT__enc__DOT__stream[149]),8);
    bufp->fullCData(oldp+543,(vlSelfRef.tb2__DOT__enc__DOT__stream[150]),8);
    bufp->fullCData(oldp+544,(vlSelfRef.tb2__DOT__enc__DOT__stream[151]),8);
    bufp->fullCData(oldp+545,(vlSelfRef.tb2__DOT__enc__DOT__stream[152]),8);
    bufp->fullCData(oldp+546,(vlSelfRef.tb2__DOT__enc__DOT__stream[153]),8);
    bufp->fullCData(oldp+547,(vlSelfRef.tb2__DOT__enc__DOT__stream[154]),8);
    bufp->fullCData(oldp+548,(vlSelfRef.tb2__DOT__enc__DOT__stream[155]),8);
    bufp->fullCData(oldp+549,(vlSelfRef.tb2__DOT__enc__DOT__stream[156]),8);
    bufp->fullCData(oldp+550,(vlSelfRef.tb2__DOT__enc__DOT__stream[157]),8);
    bufp->fullCData(oldp+551,(vlSelfRef.tb2__DOT__enc__DOT__stream[158]),8);
    bufp->fullCData(oldp+552,(vlSelfRef.tb2__DOT__enc__DOT__stream[159]),8);
    bufp->fullCData(oldp+553,(vlSelfRef.tb2__DOT__enc__DOT__stream[160]),8);
    bufp->fullCData(oldp+554,(vlSelfRef.tb2__DOT__enc__DOT__stream[161]),8);
    bufp->fullCData(oldp+555,(vlSelfRef.tb2__DOT__enc__DOT__stream[162]),8);
    bufp->fullCData(oldp+556,(vlSelfRef.tb2__DOT__enc__DOT__stream[163]),8);
    bufp->fullCData(oldp+557,(vlSelfRef.tb2__DOT__enc__DOT__stream[164]),8);
    bufp->fullCData(oldp+558,(vlSelfRef.tb2__DOT__enc__DOT__stream[165]),8);
    bufp->fullCData(oldp+559,(vlSelfRef.tb2__DOT__enc__DOT__stream[166]),8);
    bufp->fullCData(oldp+560,(vlSelfRef.tb2__DOT__enc__DOT__stream[167]),8);
    bufp->fullCData(oldp+561,(vlSelfRef.tb2__DOT__enc__DOT__stream[168]),8);
    bufp->fullCData(oldp+562,(vlSelfRef.tb2__DOT__enc__DOT__stream[169]),8);
    bufp->fullCData(oldp+563,(vlSelfRef.tb2__DOT__enc__DOT__stream[170]),8);
    bufp->fullCData(oldp+564,(vlSelfRef.tb2__DOT__enc__DOT__stream[171]),8);
    bufp->fullCData(oldp+565,(vlSelfRef.tb2__DOT__enc__DOT__stream[172]),8);
    bufp->fullCData(oldp+566,(vlSelfRef.tb2__DOT__enc__DOT__stream[173]),8);
    bufp->fullCData(oldp+567,(vlSelfRef.tb2__DOT__enc__DOT__stream[174]),8);
    bufp->fullCData(oldp+568,(vlSelfRef.tb2__DOT__enc__DOT__stream[175]),8);
    bufp->fullCData(oldp+569,(vlSelfRef.tb2__DOT__enc__DOT__stream[176]),8);
    bufp->fullCData(oldp+570,(vlSelfRef.tb2__DOT__enc__DOT__stream[177]),8);
    bufp->fullCData(oldp+571,(vlSelfRef.tb2__DOT__enc__DOT__stream[178]),8);
    bufp->fullCData(oldp+572,(vlSelfRef.tb2__DOT__enc__DOT__stream[179]),8);
    bufp->fullCData(oldp+573,(vlSelfRef.tb2__DOT__enc__DOT__stream[180]),8);
    bufp->fullCData(oldp+574,(vlSelfRef.tb2__DOT__enc__DOT__stream[181]),8);
    bufp->fullCData(oldp+575,(vlSelfRef.tb2__DOT__enc__DOT__stream[182]),8);
    bufp->fullCData(oldp+576,(vlSelfRef.tb2__DOT__enc__DOT__stream[183]),8);
    bufp->fullCData(oldp+577,(vlSelfRef.tb2__DOT__enc__DOT__stream[184]),8);
    bufp->fullCData(oldp+578,(vlSelfRef.tb2__DOT__enc__DOT__stream[185]),8);
    bufp->fullCData(oldp+579,(vlSelfRef.tb2__DOT__enc__DOT__stream[186]),8);
    bufp->fullCData(oldp+580,(vlSelfRef.tb2__DOT__enc__DOT__stream[187]),8);
    bufp->fullCData(oldp+581,(vlSelfRef.tb2__DOT__enc__DOT__stream[188]),8);
    bufp->fullCData(oldp+582,(vlSelfRef.tb2__DOT__enc__DOT__stream[189]),8);
    bufp->fullCData(oldp+583,(vlSelfRef.tb2__DOT__enc__DOT__stream[190]),8);
    bufp->fullCData(oldp+584,(vlSelfRef.tb2__DOT__enc__DOT__stream[191]),8);
    bufp->fullCData(oldp+585,(vlSelfRef.tb2__DOT__enc__DOT__stream[192]),8);
    bufp->fullCData(oldp+586,(vlSelfRef.tb2__DOT__enc__DOT__stream[193]),8);
    bufp->fullCData(oldp+587,(vlSelfRef.tb2__DOT__enc__DOT__stream[194]),8);
    bufp->fullCData(oldp+588,(vlSelfRef.tb2__DOT__enc__DOT__stream[195]),8);
    bufp->fullCData(oldp+589,(vlSelfRef.tb2__DOT__enc__DOT__stream[196]),8);
    bufp->fullCData(oldp+590,(vlSelfRef.tb2__DOT__enc__DOT__stream[197]),8);
    bufp->fullCData(oldp+591,(vlSelfRef.tb2__DOT__enc__DOT__stream[198]),8);
    bufp->fullCData(oldp+592,(vlSelfRef.tb2__DOT__enc__DOT__stream[199]),8);
    bufp->fullCData(oldp+593,(vlSelfRef.tb2__DOT__enc__DOT__stream[200]),8);
    bufp->fullCData(oldp+594,(vlSelfRef.tb2__DOT__enc__DOT__stream[201]),8);
    bufp->fullCData(oldp+595,(vlSelfRef.tb2__DOT__enc__DOT__stream[202]),8);
    bufp->fullCData(oldp+596,(vlSelfRef.tb2__DOT__enc__DOT__stream[203]),8);
    bufp->fullCData(oldp+597,(vlSelfRef.tb2__DOT__enc__DOT__stream[204]),8);
    bufp->fullCData(oldp+598,(vlSelfRef.tb2__DOT__enc__DOT__stream[205]),8);
    bufp->fullCData(oldp+599,(vlSelfRef.tb2__DOT__enc__DOT__stream[206]),8);
    bufp->fullCData(oldp+600,(vlSelfRef.tb2__DOT__enc__DOT__stream[207]),8);
    bufp->fullCData(oldp+601,(vlSelfRef.tb2__DOT__enc__DOT__stream[208]),8);
    bufp->fullCData(oldp+602,(vlSelfRef.tb2__DOT__enc__DOT__stream[209]),8);
    bufp->fullCData(oldp+603,(vlSelfRef.tb2__DOT__enc__DOT__stream[210]),8);
    bufp->fullCData(oldp+604,(vlSelfRef.tb2__DOT__enc__DOT__stream[211]),8);
    bufp->fullCData(oldp+605,(vlSelfRef.tb2__DOT__enc__DOT__stream[212]),8);
    bufp->fullCData(oldp+606,(vlSelfRef.tb2__DOT__enc__DOT__stream[213]),8);
    bufp->fullCData(oldp+607,(vlSelfRef.tb2__DOT__enc__DOT__stream[214]),8);
    bufp->fullCData(oldp+608,(vlSelfRef.tb2__DOT__enc__DOT__stream[215]),8);
    bufp->fullCData(oldp+609,(vlSelfRef.tb2__DOT__enc__DOT__stream[216]),8);
    bufp->fullCData(oldp+610,(vlSelfRef.tb2__DOT__enc__DOT__stream[217]),8);
    bufp->fullCData(oldp+611,(vlSelfRef.tb2__DOT__enc__DOT__stream[218]),8);
    bufp->fullCData(oldp+612,(vlSelfRef.tb2__DOT__enc__DOT__stream[219]),8);
    bufp->fullCData(oldp+613,(vlSelfRef.tb2__DOT__enc__DOT__stream[220]),8);
    bufp->fullCData(oldp+614,(vlSelfRef.tb2__DOT__enc__DOT__stream[221]),8);
    bufp->fullCData(oldp+615,(vlSelfRef.tb2__DOT__enc__DOT__stream[222]),8);
    bufp->fullCData(oldp+616,(vlSelfRef.tb2__DOT__enc__DOT__stream[223]),8);
    bufp->fullCData(oldp+617,(vlSelfRef.tb2__DOT__enc__DOT__stream[224]),8);
    bufp->fullCData(oldp+618,(vlSelfRef.tb2__DOT__enc__DOT__stream[225]),8);
    bufp->fullCData(oldp+619,(vlSelfRef.tb2__DOT__enc__DOT__stream[226]),8);
    bufp->fullCData(oldp+620,(vlSelfRef.tb2__DOT__enc__DOT__stream[227]),8);
    bufp->fullCData(oldp+621,(vlSelfRef.tb2__DOT__enc__DOT__stream[228]),8);
    bufp->fullCData(oldp+622,(vlSelfRef.tb2__DOT__enc__DOT__stream[229]),8);
    bufp->fullCData(oldp+623,(vlSelfRef.tb2__DOT__enc__DOT__stream[230]),8);
    bufp->fullCData(oldp+624,(vlSelfRef.tb2__DOT__enc__DOT__stream[231]),8);
    bufp->fullCData(oldp+625,(vlSelfRef.tb2__DOT__enc__DOT__stream[232]),8);
    bufp->fullCData(oldp+626,(vlSelfRef.tb2__DOT__enc__DOT__stream[233]),8);
    bufp->fullCData(oldp+627,(vlSelfRef.tb2__DOT__enc__DOT__stream[234]),8);
    bufp->fullCData(oldp+628,(vlSelfRef.tb2__DOT__enc__DOT__stream[235]),8);
    bufp->fullCData(oldp+629,(vlSelfRef.tb2__DOT__enc__DOT__stream[236]),8);
    bufp->fullCData(oldp+630,(vlSelfRef.tb2__DOT__enc__DOT__stream[237]),8);
    bufp->fullCData(oldp+631,(vlSelfRef.tb2__DOT__enc__DOT__stream[238]),8);
    bufp->fullCData(oldp+632,(vlSelfRef.tb2__DOT__enc__DOT__stream[239]),8);
    bufp->fullCData(oldp+633,(vlSelfRef.tb2__DOT__enc__DOT__stream[240]),8);
    bufp->fullCData(oldp+634,(vlSelfRef.tb2__DOT__enc__DOT__stream[241]),8);
    bufp->fullCData(oldp+635,(vlSelfRef.tb2__DOT__enc__DOT__stream[242]),8);
    bufp->fullCData(oldp+636,(vlSelfRef.tb2__DOT__enc__DOT__stream[243]),8);
    bufp->fullCData(oldp+637,(vlSelfRef.tb2__DOT__enc__DOT__stream[244]),8);
    bufp->fullCData(oldp+638,(vlSelfRef.tb2__DOT__enc__DOT__stream[245]),8);
    bufp->fullCData(oldp+639,(vlSelfRef.tb2__DOT__enc__DOT__stream[246]),8);
    bufp->fullCData(oldp+640,(vlSelfRef.tb2__DOT__enc__DOT__stream[247]),8);
    bufp->fullCData(oldp+641,(vlSelfRef.tb2__DOT__enc__DOT__stream[248]),8);
    bufp->fullCData(oldp+642,(vlSelfRef.tb2__DOT__enc__DOT__stream[249]),8);
    bufp->fullCData(oldp+643,(vlSelfRef.tb2__DOT__enc__DOT__stream[250]),8);
    bufp->fullCData(oldp+644,(vlSelfRef.tb2__DOT__enc__DOT__stream[251]),8);
    bufp->fullCData(oldp+645,(vlSelfRef.tb2__DOT__enc__DOT__stream[252]),8);
    bufp->fullCData(oldp+646,(vlSelfRef.tb2__DOT__enc__DOT__stream[253]),8);
    bufp->fullCData(oldp+647,(vlSelfRef.tb2__DOT__enc__DOT__stream[254]),8);
    bufp->fullCData(oldp+648,(vlSelfRef.tb2__DOT__enc__DOT__stream[255]),8);
    bufp->fullCData(oldp+649,(vlSelfRef.tb2__DOT__enc__DOT__stream[256]),8);
    bufp->fullCData(oldp+650,(vlSelfRef.tb2__DOT__enc__DOT__stream[257]),8);
    bufp->fullCData(oldp+651,(vlSelfRef.tb2__DOT__enc__DOT__stream[258]),8);
    bufp->fullCData(oldp+652,(vlSelfRef.tb2__DOT__enc__DOT__stream[259]),8);
    bufp->fullCData(oldp+653,(vlSelfRef.tb2__DOT__enc__DOT__stream[260]),8);
    bufp->fullCData(oldp+654,(vlSelfRef.tb2__DOT__enc__DOT__stream[261]),8);
    bufp->fullCData(oldp+655,(vlSelfRef.tb2__DOT__enc__DOT__stream[262]),8);
    bufp->fullCData(oldp+656,(vlSelfRef.tb2__DOT__enc__DOT__stream[263]),8);
    bufp->fullCData(oldp+657,(vlSelfRef.tb2__DOT__enc__DOT__stream[264]),8);
    bufp->fullCData(oldp+658,(vlSelfRef.tb2__DOT__enc__DOT__stream[265]),8);
    bufp->fullCData(oldp+659,(vlSelfRef.tb2__DOT__enc__DOT__stream[266]),8);
    bufp->fullCData(oldp+660,(vlSelfRef.tb2__DOT__enc__DOT__stream[267]),8);
    bufp->fullCData(oldp+661,(vlSelfRef.tb2__DOT__enc__DOT__stream[268]),8);
    bufp->fullCData(oldp+662,(vlSelfRef.tb2__DOT__enc__DOT__stream[269]),8);
    bufp->fullCData(oldp+663,(vlSelfRef.tb2__DOT__enc__DOT__stream[270]),8);
    bufp->fullCData(oldp+664,(vlSelfRef.tb2__DOT__enc__DOT__stream[271]),8);
    bufp->fullCData(oldp+665,(vlSelfRef.tb2__DOT__enc__DOT__stream[272]),8);
    bufp->fullCData(oldp+666,(vlSelfRef.tb2__DOT__enc__DOT__stream[273]),8);
    bufp->fullCData(oldp+667,(vlSelfRef.tb2__DOT__enc__DOT__stream[274]),8);
    bufp->fullCData(oldp+668,(vlSelfRef.tb2__DOT__enc__DOT__stream[275]),8);
    bufp->fullCData(oldp+669,(vlSelfRef.tb2__DOT__enc__DOT__stream[276]),8);
    bufp->fullCData(oldp+670,(vlSelfRef.tb2__DOT__enc__DOT__stream[277]),8);
    bufp->fullCData(oldp+671,(vlSelfRef.tb2__DOT__enc__DOT__stream[278]),8);
    bufp->fullCData(oldp+672,(vlSelfRef.tb2__DOT__enc__DOT__stream[279]),8);
    bufp->fullCData(oldp+673,(vlSelfRef.tb2__DOT__enc__DOT__stream[280]),8);
    bufp->fullCData(oldp+674,(vlSelfRef.tb2__DOT__enc__DOT__stream[281]),8);
    bufp->fullCData(oldp+675,(vlSelfRef.tb2__DOT__enc__DOT__stream[282]),8);
    bufp->fullCData(oldp+676,(vlSelfRef.tb2__DOT__enc__DOT__stream[283]),8);
    bufp->fullCData(oldp+677,(vlSelfRef.tb2__DOT__enc__DOT__stream[284]),8);
    bufp->fullCData(oldp+678,(vlSelfRef.tb2__DOT__enc__DOT__stream[285]),8);
    bufp->fullCData(oldp+679,(vlSelfRef.tb2__DOT__enc__DOT__stream[286]),8);
    bufp->fullCData(oldp+680,(vlSelfRef.tb2__DOT__enc__DOT__stream[287]),8);
    bufp->fullCData(oldp+681,(vlSelfRef.tb2__DOT__enc__DOT__stream[288]),8);
    bufp->fullCData(oldp+682,(vlSelfRef.tb2__DOT__enc__DOT__stream[289]),8);
    bufp->fullCData(oldp+683,(vlSelfRef.tb2__DOT__enc__DOT__stream[290]),8);
    bufp->fullCData(oldp+684,(vlSelfRef.tb2__DOT__enc__DOT__stream[291]),8);
    bufp->fullCData(oldp+685,(vlSelfRef.tb2__DOT__enc__DOT__stream[292]),8);
    bufp->fullCData(oldp+686,(vlSelfRef.tb2__DOT__enc__DOT__stream[293]),8);
    bufp->fullCData(oldp+687,(vlSelfRef.tb2__DOT__enc__DOT__stream[294]),8);
    bufp->fullCData(oldp+688,(vlSelfRef.tb2__DOT__enc__DOT__stream[295]),8);
    bufp->fullCData(oldp+689,(vlSelfRef.tb2__DOT__enc__DOT__stream[296]),8);
    bufp->fullCData(oldp+690,(vlSelfRef.tb2__DOT__enc__DOT__stream[297]),8);
    bufp->fullCData(oldp+691,(vlSelfRef.tb2__DOT__enc__DOT__stream[298]),8);
    bufp->fullCData(oldp+692,(vlSelfRef.tb2__DOT__enc__DOT__stream[299]),8);
    bufp->fullCData(oldp+693,(vlSelfRef.tb2__DOT__enc__DOT__stream[300]),8);
    bufp->fullCData(oldp+694,(vlSelfRef.tb2__DOT__enc__DOT__stream[301]),8);
    bufp->fullCData(oldp+695,(vlSelfRef.tb2__DOT__enc__DOT__stream[302]),8);
    bufp->fullCData(oldp+696,(vlSelfRef.tb2__DOT__enc__DOT__stream[303]),8);
    bufp->fullCData(oldp+697,(vlSelfRef.tb2__DOT__enc__DOT__stream[304]),8);
    bufp->fullCData(oldp+698,(vlSelfRef.tb2__DOT__enc__DOT__stream[305]),8);
    bufp->fullCData(oldp+699,(vlSelfRef.tb2__DOT__enc__DOT__stream[306]),8);
    bufp->fullCData(oldp+700,(vlSelfRef.tb2__DOT__enc__DOT__stream[307]),8);
    bufp->fullCData(oldp+701,(vlSelfRef.tb2__DOT__enc__DOT__stream[308]),8);
    bufp->fullCData(oldp+702,(vlSelfRef.tb2__DOT__enc__DOT__stream[309]),8);
    bufp->fullCData(oldp+703,(vlSelfRef.tb2__DOT__enc__DOT__stream[310]),8);
    bufp->fullCData(oldp+704,(vlSelfRef.tb2__DOT__enc__DOT__stream[311]),8);
    bufp->fullCData(oldp+705,(vlSelfRef.tb2__DOT__enc__DOT__stream[312]),8);
    bufp->fullCData(oldp+706,(vlSelfRef.tb2__DOT__enc__DOT__stream[313]),8);
    bufp->fullCData(oldp+707,(vlSelfRef.tb2__DOT__enc__DOT__stream[314]),8);
    bufp->fullCData(oldp+708,(vlSelfRef.tb2__DOT__enc__DOT__stream[315]),8);
    bufp->fullCData(oldp+709,(vlSelfRef.tb2__DOT__enc__DOT__stream[316]),8);
    bufp->fullCData(oldp+710,(vlSelfRef.tb2__DOT__enc__DOT__stream[317]),8);
    bufp->fullCData(oldp+711,(vlSelfRef.tb2__DOT__enc__DOT__stream[318]),8);
    bufp->fullCData(oldp+712,(vlSelfRef.tb2__DOT__enc__DOT__stream[319]),8);
    bufp->fullSData(oldp+713,(vlSelfRef.tb2__DOT__enc__DOT__stream_ind),9);
    bufp->fullSData(oldp+714,(vlSelfRef.tb2__DOT__enc__DOT__stack[0]),12);
    bufp->fullSData(oldp+715,(vlSelfRef.tb2__DOT__enc__DOT__stack[1]),12);
    bufp->fullSData(oldp+716,(vlSelfRef.tb2__DOT__enc__DOT__stack[2]),12);
    bufp->fullSData(oldp+717,(vlSelfRef.tb2__DOT__enc__DOT__stack[3]),12);
    bufp->fullSData(oldp+718,(vlSelfRef.tb2__DOT__enc__DOT__stack[4]),12);
    bufp->fullSData(oldp+719,(vlSelfRef.tb2__DOT__enc__DOT__stack[5]),12);
    bufp->fullSData(oldp+720,(vlSelfRef.tb2__DOT__enc__DOT__stack[6]),12);
    bufp->fullSData(oldp+721,(vlSelfRef.tb2__DOT__enc__DOT__stack[7]),12);
    bufp->fullSData(oldp+722,(vlSelfRef.tb2__DOT__enc__DOT__stack[8]),12);
    bufp->fullSData(oldp+723,(vlSelfRef.tb2__DOT__enc__DOT__stack[9]),12);
    bufp->fullSData(oldp+724,(vlSelfRef.tb2__DOT__enc__DOT__stack[10]),12);
    bufp->fullSData(oldp+725,(vlSelfRef.tb2__DOT__enc__DOT__stack[11]),12);
    bufp->fullSData(oldp+726,(vlSelfRef.tb2__DOT__enc__DOT__stack[12]),12);
    bufp->fullSData(oldp+727,(vlSelfRef.tb2__DOT__enc__DOT__stack[13]),12);
    bufp->fullSData(oldp+728,(vlSelfRef.tb2__DOT__enc__DOT__stack[14]),12);
    bufp->fullSData(oldp+729,(vlSelfRef.tb2__DOT__enc__DOT__stack[15]),12);
    bufp->fullSData(oldp+730,(vlSelfRef.tb2__DOT__enc__DOT__stack[16]),12);
    bufp->fullSData(oldp+731,(vlSelfRef.tb2__DOT__enc__DOT__stack[17]),12);
    bufp->fullSData(oldp+732,(vlSelfRef.tb2__DOT__enc__DOT__stack[18]),12);
    bufp->fullSData(oldp+733,(vlSelfRef.tb2__DOT__enc__DOT__stack[19]),12);
    bufp->fullSData(oldp+734,(vlSelfRef.tb2__DOT__enc__DOT__stack[20]),12);
    bufp->fullSData(oldp+735,(vlSelfRef.tb2__DOT__enc__DOT__stack[21]),12);
    bufp->fullSData(oldp+736,(vlSelfRef.tb2__DOT__enc__DOT__stack[22]),12);
    bufp->fullSData(oldp+737,(vlSelfRef.tb2__DOT__enc__DOT__stack[23]),12);
    bufp->fullSData(oldp+738,(vlSelfRef.tb2__DOT__enc__DOT__stack[24]),12);
    bufp->fullSData(oldp+739,(vlSelfRef.tb2__DOT__enc__DOT__stack[25]),12);
    bufp->fullSData(oldp+740,(vlSelfRef.tb2__DOT__enc__DOT__stack[26]),12);
    bufp->fullSData(oldp+741,(vlSelfRef.tb2__DOT__enc__DOT__stack[27]),12);
    bufp->fullSData(oldp+742,(vlSelfRef.tb2__DOT__enc__DOT__stack[28]),12);
    bufp->fullSData(oldp+743,(vlSelfRef.tb2__DOT__enc__DOT__stack[29]),12);
    bufp->fullSData(oldp+744,(vlSelfRef.tb2__DOT__enc__DOT__stack[30]),12);
    bufp->fullSData(oldp+745,(vlSelfRef.tb2__DOT__enc__DOT__stack[31]),12);
    bufp->fullSData(oldp+746,(vlSelfRef.tb2__DOT__enc__DOT__stack[32]),12);
    bufp->fullSData(oldp+747,(vlSelfRef.tb2__DOT__enc__DOT__stack[33]),12);
    bufp->fullSData(oldp+748,(vlSelfRef.tb2__DOT__enc__DOT__stack[34]),12);
    bufp->fullSData(oldp+749,(vlSelfRef.tb2__DOT__enc__DOT__stack[35]),12);
    bufp->fullSData(oldp+750,(vlSelfRef.tb2__DOT__enc__DOT__stack[36]),12);
    bufp->fullSData(oldp+751,(vlSelfRef.tb2__DOT__enc__DOT__stack[37]),12);
    bufp->fullSData(oldp+752,(vlSelfRef.tb2__DOT__enc__DOT__stack[38]),12);
    bufp->fullSData(oldp+753,(vlSelfRef.tb2__DOT__enc__DOT__stack[39]),12);
    bufp->fullSData(oldp+754,(vlSelfRef.tb2__DOT__enc__DOT__stack[40]),12);
    bufp->fullSData(oldp+755,(vlSelfRef.tb2__DOT__enc__DOT__stack[41]),12);
    bufp->fullSData(oldp+756,(vlSelfRef.tb2__DOT__enc__DOT__stack[42]),12);
    bufp->fullSData(oldp+757,(vlSelfRef.tb2__DOT__enc__DOT__stack[43]),12);
    bufp->fullSData(oldp+758,(vlSelfRef.tb2__DOT__enc__DOT__stack[44]),12);
    bufp->fullSData(oldp+759,(vlSelfRef.tb2__DOT__enc__DOT__stack[45]),12);
    bufp->fullSData(oldp+760,(vlSelfRef.tb2__DOT__enc__DOT__stack[46]),12);
    bufp->fullSData(oldp+761,(vlSelfRef.tb2__DOT__enc__DOT__stack[47]),12);
    bufp->fullSData(oldp+762,(vlSelfRef.tb2__DOT__enc__DOT__stack[48]),12);
    bufp->fullSData(oldp+763,(vlSelfRef.tb2__DOT__enc__DOT__stack[49]),12);
    bufp->fullSData(oldp+764,(vlSelfRef.tb2__DOT__enc__DOT__stack[50]),12);
    bufp->fullSData(oldp+765,(vlSelfRef.tb2__DOT__enc__DOT__stack[51]),12);
    bufp->fullSData(oldp+766,(vlSelfRef.tb2__DOT__enc__DOT__stack[52]),12);
    bufp->fullSData(oldp+767,(vlSelfRef.tb2__DOT__enc__DOT__stack[53]),12);
    bufp->fullSData(oldp+768,(vlSelfRef.tb2__DOT__enc__DOT__stack[54]),12);
    bufp->fullSData(oldp+769,(vlSelfRef.tb2__DOT__enc__DOT__stack[55]),12);
    bufp->fullSData(oldp+770,(vlSelfRef.tb2__DOT__enc__DOT__stack[56]),12);
    bufp->fullSData(oldp+771,(vlSelfRef.tb2__DOT__enc__DOT__stack[57]),12);
    bufp->fullSData(oldp+772,(vlSelfRef.tb2__DOT__enc__DOT__stack[58]),12);
    bufp->fullSData(oldp+773,(vlSelfRef.tb2__DOT__enc__DOT__stack[59]),12);
    bufp->fullSData(oldp+774,(vlSelfRef.tb2__DOT__enc__DOT__stack[60]),12);
    bufp->fullSData(oldp+775,(vlSelfRef.tb2__DOT__enc__DOT__stack[61]),12);
    bufp->fullSData(oldp+776,(vlSelfRef.tb2__DOT__enc__DOT__stack[62]),12);
    bufp->fullSData(oldp+777,(vlSelfRef.tb2__DOT__enc__DOT__stack[63]),12);
    bufp->fullCData(oldp+778,(vlSelfRef.tb2__DOT__enc__DOT__stack_ind),6);
    bufp->fullSData(oldp+779,(vlSelfRef.tb2__DOT__enc__DOT__last_rgb),12);
    bufp->fullCData(oldp+780,(vlSelfRef.tb2__DOT__enc__DOT__rcntr),6);
    bufp->fullBit(oldp+781,(vlSelfRef.tb2__DOT__clk));
    bufp->fullSData(oldp+782,(vlSelfRef.tb2__DOT__enc__DOT__drgb),15);
}
