# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/b83c/fpga/vga/src/ips/buffer_mem/buffer_mem.xci
# IP: The module: 'buffer_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/src/ips/buffer_mem/buffer_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/b83c/fpga/vga/src/ips/buffer_mem/buffer_mem.xci
# IP: The module: 'buffer_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/src/ips/buffer_mem/buffer_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
