# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc.xci
# IP: The module: 'joystick_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_adc'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc.xci
# IP: The module: 'joystick_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/vga/ips/joystick_adc/joystick_adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joystick_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
