# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/b83c/fpga/vga/ips/enc_buff/enc_buff.xci
# IP: The module: 'enc_buff' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/enc_buff/enc_buff_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_buff'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/b83c/fpga/vga/ips/enc_buff/enc_buff.xci
# IP: The module: 'enc_buff' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/enc_buff/enc_buff_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_buff'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
