# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/b83c/fpga/vga/ips/rgb_stack/rgb_stack.xci
# IP: The module: 'rgb_stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/rgb_stack/rgb_stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_stack'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/b83c/fpga/vga/ips/rgb_stack/rgb_stack.xci
# IP: The module: 'rgb_stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/vga/ips/rgb_stack/rgb_stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_stack'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
